name: "Offgrid"
description: "My first real add-on!"
version: "1.0.14"
slug: "offgrid"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_dbus: true
services:
  - mqtt:need
options:
  daly_address: null
  mqtt_user: ""
  mqtt_password: ""
  mqtt_broker: "core-mosquitto"
schema:
  daly_address: "str"
  mqtt_user: "str?"
  mqtt_password: "str?"
  mqtt_broker: "str"
