name: "Batmon"
description: "Monitor various BMS over bluetooth"
version: "0.0.26"
slug: "batmon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_dbus: true
services:
  - mqtt:need
options:
  daly_address: ""
  jbd_address: ""
  jk_address: ""
  victron_address: ""
  victron_pin: "000000"
  mqtt_user: ""
  mqtt_password: ""
  mqtt_broker: "core-mosquitto"
  concurrent_sampling: false
  keep_alive: false
  verbose_log: false
  sample_period: 1.0
schema:
  daly_address: "str?"
  jbd_address: "str?"
  jk_address: "str?"
  victron_address: "str?"
  victron_pin: "str?"
  mqtt_user: "str?"
  mqtt_password: "str?"
  mqtt_broker: "str"
  concurrent_sampling: "bool"
  keep_alive: "bool"
  verbose_log: "bool"
  sample_period: "float"
